<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <!-- parent pom -->
    <groupId>${app.parent.groupId}</groupId>
    <artifactId>${app.parent.artifactId}</artifactId>
    <version>${app.parent.version}</version>
    <!-- ════════════════════════════════════ -->

    <name>${app.parent.name}</name>
    <description>${app.parent.description}</description>
    <packaging>pom</packaging>
    <properties>
        <!-- <app.parent.packaging>pom</app.parent.packaging> -->
        <app.parent.groupId>be.freeaime</app.parent.groupId>
        <app.parent.artifactId>uptime-logger</app.parent.artifactId>
        <app.parent.name>uptime logging</app.parent.name>
        <app.parent.description>This app logs uptime in csv file. It currently only works on linux
            based operating systems.</app.parent.description>
        <app.parent.version>1.1.0</app.parent.version>
        <app.child.packaging>jar</app.child.packaging>
        <app.uptimeServiceName>uptime-logger-service</app.uptimeServiceName>
        <java.version>17</java.version>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <com.opencsv.version>5.7.1</com.opencsv.version>
        <org.apache.commons.lang3.version>3.12.0</org.apache.commons.lang3.version>
        <junit.version>4.13.1</junit.version>
    </properties>
    <modules>
        <module>uptime-logger-manager</module>
        <module>uptime-logger-service</module>
    </modules>
    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>${junit.version}</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/com.opencsv/opencsv -->
        <dependency>
            <groupId>com.opencsv</groupId>
            <artifactId>opencsv</artifactId>
            <version>${com.opencsv.version} </version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.apache.commons/commons-lang3 -->
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>${org.apache.commons.lang3.version}</version>
        </dependency>
    </dependencies>
</project>